### ISSUE TITLE
Support latest version of mermaid@10

### ISSUE THREAD

**Issue by PathVR** [snt/antora-mermaid-extension#3]
@snt 

https://github.com/mermaid-js/mermaid/blob/develop/CHANGELOG.md

As per change log CJS support is not available with latest version.

Will need to changes scripts tag
![image](https://user-images.githubusercontent.com/129958623/230852367-600c58f2-c05e-445d-ac99-b4316dc5f543.png)

**Comment by snt** [comment]
Thank you @PathVR for letting me know for the change of Mermaid.js.

I have updated the npm package too.
